/*
 * This source file was generated by the Gradle 'init' task
 */
package main.java.lab7;
import java.io.*;
import java.nio.file.Paths;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.Path;

import heap.Heap;
import java.util.*;

public class Huffman {
    static class Node implements Comparable<Node>{
        char character;
        int frequency;
        Node left;
        Node right;
        
        Node(char character, int frequency){
            this.character = character;
            this.frequency = frequency;
        }
        Node(Node left, Node right){
            this.left = left;
            this.right = right;
            this.frequency = left.frequency + right.frequency;
        }
        // method to confirm if node is a leaf via confirming no L/R children 

        boolean isitALeaf(){
            if (left == null && right == null){
                return true;
            }
            return false;
        }
        // convert character from leaf into a string 
         public String toString(){
            return isitALeaf() ? "'" + character + "'" : "*";
        }
        public int compareTo(Node other){
            return Integer.compare(this.frequency, other.frequency);
        }
        private static void buildCodeMap(Node node, String path, Map<Character, String> map){
            if (node == null) return;
            if (node.isitALeaf()){
                map.put(node.character, path);
                return;
            }
            buildCodeMap(node.left, path + "0", map);
            buildCodeMap(node.right, path + "1", map);
        }

              static String encode(String input, Map<Character, String> codeMap){
            StringBuilder strb = new StringBuilder();
            for (char ch: input.toCharArray()){
                strb.append(codeMap.get(ch));
            }
            return strb.toString();
        }

         static String decode(String encodedString, Node root){
            
         }
            

    
}

  public static void main(String[] args) {
        if (args.length < 1){
            return;
        }
        String input = "";
        try{
            input = new String(Files.readAllBytes(Paths.get(args[0])));
        } catch (IOException e) {
            return;
        }

       
     
    }
}
}