/*
 * This source file was generated by the Gradle 'init' task
 */
package main.java.lab7;
import java.io.*;
import java.nio.file.Paths;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.Path;

import heap.Heap;
import java.util.*;

public class Huffman {
    
    
}
