/*
 * This source file was generated by the Gradle 'init' task
 */
package lab7;
import java.util.HashMap;
import java.util.Scanner;
import java.io.*;


public class Huffman {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Huffman().getGreeting());
    }
}
